
arch ?= UNKNOWN
include ../setup/Make.$(arch)

HPCGSRC = ../HPCG_SRC_PATH/src
VESRC = ../HPCG_SRC_PATH/llvmve

LLVMSRC = vel_hpcg_kernels.cpp
LLVMOBJ = $(patsubst %.cpp,%.o,$(LLVMSRC))

NCPPSRC = 
NCPPOBJ = $(patsubst %.cpp,%.o,$(NCPPSRC))

$(LLVMOBJ): %.o: $(VESRC)/%.cpp
	$(LLVM_VE) -fPIC $(LLVM_VE_FLAGS) -I$(HPCGSRC) -I$(VESRC) -o $@ -c $<

clean:
	rm *.o *.L *.LL *.so

.PHONE: clean

